-- PostgreSQL schema for Django 4.2 authentication and content type tables.
-- Mirrors the structure produced by ``python manage.py migrate`` for the
-- built-in ``auth`` and ``contenttypes`` apps when using the default
-- ``AbstractUser`` implementation.

-- ``auth_group``
CREATE TABLE auth_group (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL UNIQUE
);
CREATE INDEX auth_group_name_a6ea08ec_like ON auth_group (name varchar_pattern_ops);

-- ``django_content_type``
CREATE TABLE django_content_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_label VARCHAR(100) NOT NULL,
    model VARCHAR(100) NOT NULL,
    CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model)
);
CREATE INDEX django_content_type_app_label_c80f0c39_like
    ON django_content_type (app_label varchar_pattern_ops);
CREATE INDEX django_content_type_model_76bd3d3b_like
    ON django_content_type (model varchar_pattern_ops);

-- ``auth_permission``
CREATE TABLE auth_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    content_type_id BIGINT NOT NULL,
    codename VARCHAR(100) NOT NULL,
    CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq
        UNIQUE (content_type_id, codename),
    CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co
        FOREIGN KEY (content_type_id)
        REFERENCES django_content_type (id)
        ON DELETE CASCADE
);
CREATE INDEX auth_permission_content_type_id_2f476e4b
    ON auth_permission (content_type_id);
CREATE INDEX auth_permission_codename_01ab375a_like
    ON auth_permission (codename varchar_pattern_ops);

-- ``auth_group_permissions`` (many-to-many table)
CREATE TABLE auth_group_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq
        UNIQUE (group_id, permission_id),
    CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id
        FOREIGN KEY (group_id)
        REFERENCES auth_group (id)
        ON DELETE CASCADE,
    CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_permission_id
        FOREIGN KEY (permission_id)
        REFERENCES auth_permission (id)
        ON DELETE CASCADE
);
CREATE INDEX auth_group_permissions_group_id_b120cbf9
    ON auth_group_permissions (group_id);
CREATE INDEX auth_group_permissions_permission_id_84c5c92e
    ON auth_group_permissions (permission_id);

-- ``auth_user``
CREATE TABLE auth_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password VARCHAR(128) NOT NULL,
    last_login TIMESTAMPTZ NULL,
    is_superuser BOOLEAN NOT NULL DEFAULT FALSE,
    username VARCHAR(150) NOT NULL UNIQUE,
    first_name VARCHAR(150) NOT NULL DEFAULT ''::VARCHAR,
    last_name VARCHAR(150) NOT NULL DEFAULT ''::VARCHAR,
    email VARCHAR(254) NOT NULL DEFAULT ''::VARCHAR,
    is_staff BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    date_joined TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX auth_user_username_6821ab7c_like ON auth_user (username varchar_pattern_ops);

-- ``auth_user_groups`` (many-to-many table)
CREATE TABLE auth_user_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq
        UNIQUE (user_id, group_id),
    CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id
        FOREIGN KEY (group_id)
        REFERENCES auth_group (id)
        ON DELETE CASCADE,
    CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id
        FOREIGN KEY (user_id)
        REFERENCES auth_user (id)
        ON DELETE CASCADE
);
CREATE INDEX auth_user_groups_user_id_6a12ed8b
    ON auth_user_groups (user_id);
CREATE INDEX auth_user_groups_group_id_97559544
    ON auth_user_groups (group_id);

-- ``auth_user_user_permissions`` (many-to-many table)
CREATE TABLE auth_user_user_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq
        UNIQUE (user_id, permission_id),
    CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_permission_id
        FOREIGN KEY (permission_id)
        REFERENCES auth_permission (id)
        ON DELETE CASCADE,
    CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id
        FOREIGN KEY (user_id)
        REFERENCES auth_user (id)
        ON DELETE CASCADE
);
CREATE INDEX auth_user_user_permissions_user_id_a95ead1b
    ON auth_user_user_permissions (user_id);
CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c
    ON auth_user_user_permissions (permission_id);

